// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQI3XBRmWEAAgUVCUTiEue1-RFvUd1Jbg',
    appId: '1:701498491294:web:f1953f8e077ecd8ed2168f',
    messagingSenderId: '701498491294',
    projectId: 'popcornx-29d66',
    authDomain: 'popcornx-29d66.firebaseapp.com',
    storageBucket: 'popcornx-29d66.firebasestorage.app',
    measurementId: 'G-2WP2BQN78F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_IbaBMhFC_ObmAXy61b6grDNBWxBACY',
    appId: '1:701498491294:android:24b25d3669e124afd2168f',
    messagingSenderId: '701498491294',
    projectId: 'popcornx-29d66',
    storageBucket: 'popcornx-29d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdtpJSaxGL6JU0WKbu1rS732Y9lkQUfPY',
    appId: '1:701498491294:ios:511a9556023db136d2168f',
    messagingSenderId: '701498491294',
    projectId: 'popcornx-29d66',
    storageBucket: 'popcornx-29d66.firebasestorage.app',
    androidClientId: '701498491294-t2jcrdg4aj8je4guen3466v7d7qrde9p.apps.googleusercontent.com',
    iosClientId: '701498491294-cdkof4elbcj5fd9f4j66q90hb9i4vfth.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdtpJSaxGL6JU0WKbu1rS732Y9lkQUfPY',
    appId: '1:701498491294:ios:511a9556023db136d2168f',
    messagingSenderId: '701498491294',
    projectId: 'popcornx-29d66',
    storageBucket: 'popcornx-29d66.firebasestorage.app',
    androidClientId: '701498491294-t2jcrdg4aj8je4guen3466v7d7qrde9p.apps.googleusercontent.com',
    iosClientId: '701498491294-cdkof4elbcj5fd9f4j66q90hb9i4vfth.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQI3XBRmWEAAgUVCUTiEue1-RFvUd1Jbg',
    appId: '1:701498491294:web:91295638ed7ab202d2168f',
    messagingSenderId: '701498491294',
    projectId: 'popcornx-29d66',
    authDomain: 'popcornx-29d66.firebaseapp.com',
    storageBucket: 'popcornx-29d66.firebasestorage.app',
    measurementId: 'G-XEF9XY6NK7',
  );

}