// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrpIBJIyknFQ7FdlwTxTrqyqqtO4URm7g',
    appId: '1:486682269384:web:55f2058cf5fbbe460437fd',
    messagingSenderId: '486682269384',
    projectId: 'baitap-24951',
    authDomain: 'baitap-24951.firebaseapp.com',
    storageBucket: 'baitap-24951.firebasestorage.app',
    measurementId: 'G-KN24YJE9E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjz80kUg1RU48BZkPUAg4SaObRP5w0O00',
    appId: '1:486682269384:android:e7cad451698176e50437fd',
    messagingSenderId: '486682269384',
    projectId: 'baitap-24951',
    storageBucket: 'baitap-24951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdefkNNZLkzvIRF8H7Hj0Gryi3HiynKc',
    appId: '1:486682269384:ios:90dbe47e873826330437fd',
    messagingSenderId: '486682269384',
    projectId: 'baitap-24951',
    storageBucket: 'baitap-24951.firebasestorage.app',
    iosBundleId: 'com.example.baitapthuchanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdefkNNZLkzvIRF8H7Hj0Gryi3HiynKc',
    appId: '1:486682269384:ios:90dbe47e873826330437fd',
    messagingSenderId: '486682269384',
    projectId: 'baitap-24951',
    storageBucket: 'baitap-24951.firebasestorage.app',
    iosBundleId: 'com.example.baitapthuchanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrpIBJIyknFQ7FdlwTxTrqyqqtO4URm7g',
    appId: '1:486682269384:web:fe84075d5ad382680437fd',
    messagingSenderId: '486682269384',
    projectId: 'baitap-24951',
    authDomain: 'baitap-24951.firebaseapp.com',
    storageBucket: 'baitap-24951.firebasestorage.app',
    measurementId: 'G-Z69YW19XN2',
  );
}
